{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-r2rtf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/r2rtf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/r2rtf/r2rtf_{{ version }}.tar.gz
  sha256: f0c15dbf066b76ef245834a0e180bb20c04a91e9afc583be8189225bc14eea84

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('r2rtf')"           # [not win]
    - "\"%R%\" -e \"library('r2rtf')\""  # [win]

about:
  home: https://merck.github.io/r2rtf/, https://github.com/Merck/r2rtf
  license: GPL-3.0-only
  summary: Create production-ready Rich Text Format (RTF) table and figure with flexible format.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
